server:
  port: 8040
spring:
  application:
    name: aes-rsa-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756

# localhost:8040/aes-rsa-client/hello
# localhost:8040/aes-rsa-server/hello