server:
  port: 8889

spring:
#  boot:
#    admin:
#      url: http://localhost:8889 #监控服务器地址
#      client:
#        name: ${spring.application.name} #客户端名称
  application:
    name: springboot-admin
  mail:
    host: smtp.qq.com
    username: XX@qq.com
    password: mebaqizkkzjcqgfbe
    properties:
      mail:
        smtp:
          ssl:
           enable: true
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
    port: 465
  boot:
    admin:
      notify:
        mail:
          to: XX@qq.com
          from: XX@qq.com
          ignore-changes: "UNKNOWN"
          subject: "#{application.name} (#{application.id}) is #{to.status} wpf"
          text: "#{application.name} (#{application.id})\nstatus changed from #{from.status} to #{to.status}\n\n#{application.healthUrl} wpf"
      url:
      client:
        service-url:
        metadata:
          user.name: admin
          user.password: admin
      username: admin
      password: admin
# 一些版本信息
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  security:
    enabled: false
