server:
  port: 8889

spring:
  boot:
    admin:
      url: http://localhost:8889 #监控服务器地址
      client:
        name: wpf_server #客户端名称
  application:
    name: springboot-admin

# 一些版本信息
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
